FROM        ubuntu
RUN         apt update -y
RUN         apt install nginx -y
CMD         ["nginx", "-g", "daemon off;"]


####To run Nginx within a Docker container          CMD         ["nginx", "-g", "daemon off;"]
