version: "3.9"
services:
  frontend:
    image: .dkr.ecr.us-east-1.amazonaws.com/frontend:0.0.9
    container_name: frontend
    ports:
      - "80:80"
    depends_on:

  user:
    image: .dkr.ecr.us-east-1.amazonaws.com/user:0.0.3
    container_name: user
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis